name: flutter_camera_processing
description: A new Flutter project.
version: 0.0.1+1
# homepage:
environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.10.4
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  image: ^3.3.0
  image_picker: ^0.8.7
  path_provider: ^2.0.14
  share_plus: ^6.3.4

dev_dependencies:
  ffigen: ^7.2.4 # dart run ffigen
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.markosyan.flutter_camera_processing
        pluginClass: FlutterCameraProcessingPlugin
      ios:
        pluginClass: FlutterCameraProcessingPlugin

ffigen:
  name: GeneratedBindings
  description: Bindings to opencv and zxing.
  output: "lib/generated_bindings.dart"
  headers:
    entry-points:
      - "ios/Classes/src/native_opencv.h"
      - "ios/Classes/src/native_zxing.h"
  # functions:
  #   include:
  #     - 'opencvVersion'
  #     - 'opencvProcessStream'
  #     - 'zxingVersion'
  #     - 'zxingRead'
  #     - 'zxingEncode'
